routes/web.php
<?php

use App\Http\Controllers\DBBackupController;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\PlottingController;
use App\Http\Controllers\ProfilController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\MahasiswaController;
use App\Http\Controllers\IssuesController;
use App\Http\Controllers\MilestoneController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\NilaiFaseController;
use App\Http\Controllers\PenilaianMingguan;
use App\Http\Controllers\ExportController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/welcome', function () {
    return view('welcome');
});

Route::get('/lading', function () {
    return view('lading');
});

Route::permanentRedirect('/', '/lading');

Route::get('/login', function () {
    return view('login');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('profil', ProfilController::class)->except('destroy');
Route::get('/Search', [AdminController::class, 'search']);
Route::get('/Search_Mahasiswa', [AdminController::class, 'search_Mahasiswa']);
Route::get('/Dosen_Pengampu', [AdminController::class, 'dosen_pengampu']);
Route::get('nilai-mingguan/{project_id}/{kode_matakuliah}/edit', [PenilaianMingguan::class, 'edit'])->name('nilai-mingguan.custom_edit');
Route::get('/manage-dosen/rekap/{project_id}', [NilaiFaseController::class, 'rekap'])->name('manage-dosen.rekap');
Route::get('/nilai-mingguan/rekap/{project_id}/{kode_matakuliah}', [PenilaianMingguan::class, 'rekap'])->name('nilai-mingguan.rekap');
Route::post('/get-aspek-by-fase', [NilaiFaseController::class, 'getAspekByFase'])->name('get.aspek.by.fase');
Route::get('/manage-dosen/edit/{project_id}', [NilaiFaseController::class, 'edit'])->name('manage-dosen.edit');
Route::get('/manage-dosen/detail/{project_id}', [NilaiFaseController::class, 'detail'])->name('manage-dosen.detail');
Route::get('/manage-penilaianmingguan/detail/{project_id}', [PenilaianMingguan::class, 'detail'])->name('manage-penilaianmingguan.detail');


Route::resource('manage-user', UserController::class);
Route::resource('manage-admin', AdminController::class);
Route::resource('manage-dosen', NilaiFaseController::class);
Route::resource('nilai-mingguan', PenilaianMingguan::class);
Route::post('/nilai-ujian', [PenilaianMingguan::class, 'ujian'])->name('nilai.ujian');
Route::resource('manage-role', RoleController::class);
Route::resource('manage-menu', MenuController::class);
Route::resource('manage-plotting', PlottingController::class);
Route::resource('manage-project', MahasiswaController::class);
Route::resource('manage-milestone', MilestoneController::class);
Route::resource('manage-issues', IssuesController::class);
Route::post('/issues/update', [IssuesController::class, 'store'])->name('issues.update');
Route::post('manage-issues/store/{milestone_id}', [IssuesController::class, 'store'])->name('manage-issue.store');
Route::get('manage-issues/{milestone_id}', [IssuesController::class, 'show'])->name('manage-issues.show');
Route::get('/manage-project/{project_id}/{nip}', [MahasiswaController::class, 'show'])->name('manage-project.show');
Route::get('/manage-milestone/insert/{project_id}', [MahasiswaController::class, 'create'])->name('manage-project.create');
Route::get('/manage-project/{milestone_id}/detail', [MahasiswaController::class, 'show'])->name('manage-project.detail');
Route::get('/fetch-issues/{milestoneId}', [MahasiswaController::class, 'fetchIssues']);
Route::post('/update-issues', [MahasiswaController::class, 'updateIssues'])->name('update-issues');
Route::get('manage-issues/insert/{milestone_id}', [IssuesController::class, 'create'])->name('manage-issue.create');
Route::post('manage-milestone', [IssuesController::class, 'store'])->name('milestone.store');
Route::resource('manage-permission', PermissionController::class)->only('store', 'destroy');
Route::get('/manage-plotting/{project_id}', 'PlottingController@detail')->name('manage-plotting.detail');
Route::delete('/hapus-dosen-pengampu/{id_dosen_pengampu}', [AdminController::class, 'hapus']);
Route::post('/issues/update/{milestone_id}', [IssuesController::class, 'update'])->name('issues.update');
Route::delete('/manage-project/{project_id}/{milestone_id}', [MahasiswaController::class, 'destroy'])->name('manage-project.destroy');
Route::post('/export', [ExportController::class, 'export'])->name('export');

Route::get('dbbackup', [DBBackupController::class, 'DBDataBackup']);

app/Models/Dosen.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Dosen extends Model
{
    use HasFactory;

    public $timestamps = false;

    protected $table = 'dosen';
    protected $primaryKey = 'nip';

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = 
    [
        'id_user',
        'nip',
        'nama_dosen'
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'nip' => 'string',
    ];

    public function mata_kuliah()
    {
        return $this->hasMany(MataKuliah::class, 'nip', 'nip');
    }
} 

resources/views/dosen/edit.blade.php
@extends('layouts.app')

@push('css')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
@endpush

@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-md-6">
                    <label for="fase_id">Pilih Fase</label>
                    <div class="d-flex justify-content-between align-items-center">
                        <form method="get" action="" class="mr-5 flex-grow-1">
                            <select name="fase_id" id="fase_id" class="form-control" onchange="this.form.submit()">
                                @foreach ($fase_project as $fase)
                                    <option value="{{ $fase->fase_id }}"
                                        {{ request()->get('fase_id') == $fase->fase_id ? 'selected' : '' }}>
                                        {{ $fase->nama_fase }}
                                    </option>
                                @endforeach
                            </select>
                        </form>
                        <a href="{{ route('manage-dosen.rekap', $project->project_id) }}"
                            class="btn btn-sm btn-outline-info ml-auto mr-0">Rekap Nilai</a>
                    </div>
                </div>


            <!-- <div class="col-md-6">
                                        <label for="fase_id">Pilih Fase</label>
                                        <select name="fase_id" id="fase_id" class="form-control">
                                                
                                        </select>
                                    </div> -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                </ol>
            </div>
        </div>
    </div>
</div>
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h5 class="card-title m-0"></h5>
                        <div class="card-tools">
                            <a href="{{ route('manage-dosen.index') }}" class="btn btn-tool"><i class="fas fa-arrow-alt-circle-left"></i></a>
                        </div>
                    </div>
                    <form action="{{ route('manage-dosen.store') }}" method="post">
                        @csrf
                        <input type="hidden" name="nip" value="{{$dosen['nip']}}">
                        <input type="hidden" name="project_id" value="{{$project['project_id']}}">
                        <div class="card-body">
                            <h5 class="card-title m-0">Judul Project : {{ $project->judul_project }} </h5><br>
                            <h5 class="card-title m-0">Kode Project : {{ $project->kode_pbl }} </h5>
                        </div>
                        <div class="card-body">

                            <table id="datatable-main" class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>NIM</th>
                                        <th>Nama Mahasiswa</th>
                                        @foreach ($aspek as $row)
                                        <th>{{ $row->nama_aspek }}
                                            <input type="hidden" name="aspek_id[]" value="{{ $row->aspek_id }}">
                                        </th>
                                        @endforeach
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($project->mahasiswa as $mahasiswa)
                                    <tr>
                                        <td>{{ $loop->iteration }}.</td>
                                        <td>{{ $mahasiswa->nim }}
                                            <input type="hidden" name="nim[]" value="{{ $mahasiswa->nim }}">
                                        </td>
                                        <td>{{ $mahasiswa->nama_lengkap }}</td>
                                        @foreach ($aspek as $row)

                                        <td>
                                            @foreach ($nilai_aspek as $nilai)
                                            @if ($nilai->nim == $mahasiswa->nim && $nilai->aspek_id == $row->aspek_id)
                                            <input type="number" value="{{ $nilai->nilai_aspek }}" name="nilai_aspek[{{ $mahasiswa->nim }}][{{ $row->aspek_id }}]" class="form-control rounded-md" style="width: 70px;" required>
                                            @endif
                                            @endforeach
                                            @if (!$nilai_aspek->contains('nim', $mahasiswa->nim) || !$nilai_aspek->contains('aspek_id', $row->aspek_id))
                                            <input type="number" value="" name="nilai_aspek[{{ $mahasiswa->nim }}][{{ $row->aspek_id }}]" class="form-control rounded-md" style="width: 70px;" required>
                                            @endif
                                        

                                        </td>
                                        @endforeach
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-info btn-block btn-flat"><i class="fa fa-save"></i> Simpan</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('js')
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
<script>
    $(document).ready(function() {
        $('#fase_id').select2({
            placeholder: 'Pilih Fase'
        });

        $('#fase_id').change(function() {
            var fase_id = $(this).val();
            $.ajax({
                url: '{{ route("get.aspek.by.fase") }}',
                type: 'POST',
                data: {
                    '_token': '{{ csrf_token() }}',
                    'fase_id': fase_id
                },
                success: function(response) {
                    // Memperbarui nama aspek untuk setiap baris dalam tabel
                    $.each(response, function(nim, nama_aspek) {
                        $('.nama_aspek_' + nim).text(nama_aspek);
                    });
                }
            });
        });
    });
</script>
@endpush

resources/views/dosen/plotting.blade.php
@extends('layouts.app')
@push('css')
@endpush
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6 text-uppercase">
                    <h4 class="m-0">Tambah Ketua dan Anggota</h4>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-primary card-outline">
                        <div class="card-header">
                            <h5 class="card-title m-0"></h5>
                            <div class="card-tools">
                                <a href="{{ route('manage-admin.index') }}" class="btn btn-tool"><i
                                        class="fas fa-arrow-alt-circle-left"></i></a>
                            </div>
                        </div>
                        <form action="{{ route('manage-plotting.store') }}" method="post">
                            @csrf
                            <div class="card-body">
                                <div class="form-group">
                                    <label>Project Manager</label>
                                    <input value="{{ $project->dosen->nama_dosen }}" type="text" name="project manager" class="form-control" placeholder="project manager" readonly>
                                </div>
                                <input type="hidden" name="project_id" value="{{ $project->project_id }}">
                                <div class="form-group ">
                                    <label for="nim_ketua">Ketua Mahasiswa</label>
                                    <input type="text" name="nim_ketua" id="nim_ketua" class="form-control" placeholder="Nama Ketua">
                                    <div class="form-group d-flex align-items-center">
                                        <span id="clearValue" class="mr-3" style="display: none; cursor: pointer;">
                                        <i class="fas fa-times"></i>
                                        </span>
                                        <div id="selectedValue" class="selected-value-container flex-grow-1"></div>
                                    </div>
                                </div>
                                <input type="hidden" id="hidden_nim_ketua" name="nim_ketua">
                                <div class="form-group">
                                    <label for="nim_anggota">Anggota</label>
                                    <input type="text" name="nim_anggota" id="nim_anggota" class="form-control" placeholder="Anggota">
                                    <div class="d-flex align-items-center">
                                        <span id="clearValue2" class="ml-2" style="display: none; cursor: pointer;">
                                        <i class="fas fa-times"></i> <!-- Ganti dengan ikon hapus yang sesuai -->
                                        </span>
                                        <div id="selectedValue2" class="selected-value-container flex-grow-1"></div>
                                    </div>
                                </div>
                                <!-- Input tersembunyi untuk menyimpan nim anggota -->
                                <input type="hidden" id="hidden_nim_anggota" name="nim_anggota[]">
                            <div class="card-footer">
                                <button type="submit" class="btn btn-info btn-block btn-flat"><i class="fa fa-save"></i>
                                    Simpan</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('js')
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
<script>
    $(document).ready(function() {
    $('#nim_ketua, #nim_anggota').autocomplete({
        source: function(request, response) {
            $.ajax({
                url: '/Search_Mahasiswa',
                dataType: 'json',
                data: {
                    term: request.term
                },
                success: function(data) {
                    response($.map(data, function(item) {
                        var labelHtml = item.nama_lengkap + ' - ' + item.nim ;
                        return {
                            label: labelHtml,
                            value: item.nama_lengkap,
                            nim: item.nim,
                            is_ketua: $('#nim_ketua').is(':focus')
                        };
                    }));
                }
            });
        },
        select: function(event, ui) {
            $(this).val(ui.item.value);
            if ($(this).attr('id') === 'nim_anggota') {
                // Menambahkan input baru ketika anggota dipilih
                addAnggotaInput(ui.item.label, ui.item.nim, ui.item.value);
            } else if ($(this).attr('id') === 'nim_ketua') {
                $('#hidden_nim_ketua').val(ui.item.nim);
                $('#selectedValue').html(`<div class="d-flex align-items-center mt-2">
                                            <input type="text" class="form-control nim_anggota flex-grow-1" value=" ${ui.item.value} " readonly>
                                        </div>`);
                $('#clearValue').show();
            }
            return false;
        },
        minLength: 2,
        open: function(event, ui) {
            $(this).autocomplete("widget").css({
                "width": "auto",
                "padding": "10px",
                "border": "1px solid #ccc",
                "list-style": "none",
                "border-radius": "5px",
                "box-shadow": "0 4px 8px 0 rgba(0,0,0,0.2)",
                "background-color": "#fff",
                "position": "absolute",
                "z-index": "1000"
            });
        }
    });

    $('#clearValue').click(function() {
        $('#nim_ketua').val('');
        $('#selectedValue').text('');
        $(this).hide();
    });

    $('#clearValue2').click(function() {
        $('#nim_anggota').val('');
        $('#selectedValue2').text('');
        $(this).hide();
    });

    // Function to add new anggota input dynamically
    // Function to add new anggota input dynamically
// Function to add new anggota input dynamically
function addAnggotaInput(label, nim, value) {
    if (nim) { // Memastikan nim tidak kosong sebelum menambahkan input
        var anggotaHtml = `
        <div class="form-group d-flex align-items-center">
            <div>
                <span class="clearValue2 mr-3" style="cursor: pointer;">
                <i class="fas fa-times"></i>
                </span>
            </div>
            <input type="text" class="form-control nim_anggota flex-grow-1" value="${value}" readonly>
            <input type="hidden" class="hidden_nim_anggota" name="nim_anggota[]" value="${nim}">
        </div>`;
        $('#nim_anggota').closest('.form-group').after(anggotaHtml);
    }

    // Clear the input value and hide clear button after adding new anggota
    $('#nim_anggota').val('');
    $('#selectedValue2').text('');
    $('#clearValue2').hide();
}

    // Dynamic event delegation for clearing anggota input
    $(document).on('click', '.clearValue2', function() {
        $(this).closest('.form-group').remove();
    });
});

</script>
@endpush

resources/views/dosen/rekap.blade.php
@extends('layouts.app')

@push('css')
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
@endpush

@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-md-6"></div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right"></ol>
            </div>
        </div>
    </div>
</div>
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h5 class="card-title m-0"></h5>
                        <label for="fase_id">Rekapitulasi</label>
                        <div class="card-tools">
                            <a href="{{ route('manage-dosen.index') }}" class="btn btn-tool"><i class="fas fa-arrow-alt-circle-left"></i></a>
                        </div>
                    </div>
                    <form action="{{ route('manage-dosen.store') }}" method="post">
                        @csrf
                        <input type="hidden" name="nip" value="{{ $dosen['nip'] }}">
                        <input type="hidden" name="project_id" value="{{ $project['project_id'] }}">
                        <div class="card-body">
                            <h5 class="card-title m-0">Judul Project: {{ $project->judul_project }}</h5><br>
                            <h5 class="card-title m-0">Kode Project: {{ $project->kode_pbl }}</h5>
                        </div>
                        <div class="card-body">
                            <table id="datatable-main" class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>NIM</th>
                                        <th>Nama Mahasiswa</th>
                                        @foreach ($fase_project as $row)
                                        <th>{{ $row->nama_fase }}
                                            <input type="hidden" name="fase_id[]" value="{{ $row->fase_id }}">
                                        </th>
                                        @endforeach
                                        <th>Rata-rata</th>
                                    </tr>
                                </thead>
                                <tbody>
                                @foreach ($project->mahasiswa as $mahasiswa)
                                @php
                                    $nilai_aspek_mahasiswa = $nilai_aspek_grouped->get($mahasiswa->nim, collect());
                                    $nilai_fase = [];
                                    foreach ($fase_project as $fase) {
                                        $nilai_fase[$fase->fase_id] = [];
                                    }
                                @endphp
                    

                                @if ($nilai_aspek_mahasiswa)
                                    @foreach ($nilai_aspek_mahasiswa as $fase_id => $nilai)
                                        @foreach ($nilai as $aspek_nilai)
                                            @php
                                                $nilai_fase[$fase_id][] = $aspek_nilai->nilai_aspek;
                                            @endphp
                                        @endforeach
                                    @endforeach
                                @endif    

                                <tr>
                                    <td>{{ $loop->iteration }}.</td>
                                    <td>{{ $mahasiswa->nim }}
                                        <input type="hidden" name="nim[]" value="{{ $mahasiswa->nim }}">
                                    </td>
                                    <td>{{ $mahasiswa->nama_lengkap }}</td>
                                    @php
                                        $total_avg = 0;
                                        $total_phases = count($fase_project);
                                    @endphp
                                    @foreach ($fase_project as $fase)
                                    <td>
                                        @php
                                            $nilai = $nilai_fase[$fase->fase_id];
                                            $avg = !empty($nilai) ? array_sum($nilai) / count($nilai) : 0;
                                            $total_avg += $avg;
                                        @endphp
                                        {{ number_format($avg, 2) }}
                                    </td>
                                    @endforeach

                                    <td>
                                    @php
                                        $final_avg = $total_avg / $total_phases;
                                    @endphp
                                    {{ number_format($final_avg, 2) }}
                                    </td>
                                </tr>
                                @endforeach
                            </tbody> 
                        </table>
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('js')
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
<script>
    $(document).ready(function() {
        $('#fase_id').select2({
            placeholder: 'Pilih Fase'
        });

        $('#fase_id').change(function() {
            var fase_id = $(this).val();
            $.ajax({
                url: '{{ route("get.aspek.by.fase") }}',
                type: 'POST',
                data: {
                    '_token': '{{ csrf_token() }}',
                    'fase_id': fase_id
                },
                success: function(response) {
                    // Memperbarui nama aspek untuk setiap baris dalam tabel
                    $.each(response, function(nim, nama_aspek) {
                        $('.nama_aspek_' + nim).text(nama_aspek);
                    });
                }
            });
        });
    });
</script>
@endpush