routes/web.php
<?php

use App\Http\Controllers\DBBackupController;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\PlottingController;
use App\Http\Controllers\ProfilController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\MahasiswaController;
use App\Http\Controllers\IssuesController;
use App\Http\Controllers\MilestoneController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\NilaiFaseController;
use App\Http\Controllers\PenilaianMingguan;
use App\Http\Controllers\ExportController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/welcome', function () {
    return view('welcome');
});

Route::get('/lading', function () {
    return view('lading');
});

Route::permanentRedirect('/', '/lading');

Route::get('/login', function () {
    return view('login');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('profil', ProfilController::class)->except('destroy');
Route::get('/Search', [AdminController::class, 'search']);
Route::get('/Search_Mahasiswa', [AdminController::class, 'search_Mahasiswa']);
Route::get('/Dosen_Pengampu', [AdminController::class, 'dosen_pengampu']);
Route::get('nilai-mingguan/{project_id}/{kode_matakuliah}/edit', [PenilaianMingguan::class, 'edit'])->name('nilai-mingguan.custom_edit');
Route::get('/manage-dosen/rekap/{project_id}', [NilaiFaseController::class, 'rekap'])->name('manage-dosen.rekap');
Route::get('/nilai-mingguan/rekap/{project_id}/{kode_matakuliah}', [PenilaianMingguan::class, 'rekap'])->name('nilai-mingguan.rekap');
Route::post('/get-aspek-by-fase', [NilaiFaseController::class, 'getAspekByFase'])->name('get.aspek.by.fase');
Route::get('/manage-dosen/edit/{project_id}', [NilaiFaseController::class, 'edit'])->name('manage-dosen.edit');
Route::get('/manage-dosen/detail/{project_id}', [NilaiFaseController::class, 'detail'])->name('manage-dosen.detail');
Route::get('/manage-penilaianmingguan/detail/{project_id}', [PenilaianMingguan::class, 'detail'])->name('manage-penilaianmingguan.detail');


Route::resource('manage-user', UserController::class);
Route::resource('manage-admin', AdminController::class);
Route::resource('manage-dosen', NilaiFaseController::class);
Route::resource('nilai-mingguan', PenilaianMingguan::class);
Route::post('/nilai-ujian', [PenilaianMingguan::class, 'ujian'])->name('nilai.ujian');
Route::resource('manage-role', RoleController::class);
Route::resource('manage-menu', MenuController::class);
Route::resource('manage-plotting', PlottingController::class);
Route::resource('manage-project', MahasiswaController::class);
Route::resource('manage-milestone', MilestoneController::class);
Route::resource('manage-issues', IssuesController::class);
Route::post('/issues/update', [IssuesController::class, 'store'])->name('issues.update');
Route::post('manage-issues/store/{milestone_id}', [IssuesController::class, 'store'])->name('manage-issue.store');
Route::get('manage-issues/{milestone_id}', [IssuesController::class, 'show'])->name('manage-issues.show');
Route::get('/manage-project/{project_id}/{nip}', [MahasiswaController::class, 'show'])->name('manage-project.show');
Route::get('/manage-milestone/insert/{project_id}', [MahasiswaController::class, 'create'])->name('manage-project.create');
Route::get('/manage-project/{milestone_id}/detail', [MahasiswaController::class, 'show'])->name('manage-project.detail');
Route::get('/fetch-issues/{milestoneId}', [MahasiswaController::class, 'fetchIssues']);
Route::post('/update-issues', [MahasiswaController::class, 'updateIssues'])->name('update-issues');
Route::get('manage-issues/insert/{milestone_id}', [IssuesController::class, 'create'])->name('manage-issue.create');
Route::post('manage-milestone', [IssuesController::class, 'store'])->name('milestone.store');
Route::resource('manage-permission', PermissionController::class)->only('store', 'destroy');
Route::get('/manage-plotting/{project_id}', 'PlottingController@detail')->name('manage-plotting.detail');
Route::delete('/hapus-dosen-pengampu/{id_dosen_pengampu}', [AdminController::class, 'hapus']);
Route::post('/issues/update/{milestone_id}', [IssuesController::class, 'update'])->name('issues.update');
Route::delete('/manage-project/{project_id}/{milestone_id}', [MahasiswaController::class, 'destroy'])->name('manage-project.destroy');
Route::post('/export', [ExportController::class, 'export'])->name('export');

Route::get('dbbackup', [DBBackupController::class, 'DBDataBackup']);

resources/views/admin/create.blade.php
@extends('layouts.app')
@push('css')
@endpush
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6 text-uppercase">
                    <h4 class="m-0">Tambah Proyek</h4>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-primary card-outline">
                        <div class="card-header">
                            <h5 class="card-title m-0"></h5>
                            <div class="card-tools">
                                <a href="{{ route('manage-admin.index') }}" class="btn btn-tool"><i
                                        class="fas fa-arrow-alt-circle-left"></i></a>
                            </div>
                        </div>
                        <form action="{{ route('manage-admin.store') }}" method="post">
                            @csrf
                            <div class="card-body">
                                <div class="form-group">
                                    <label>Kode PBL</label>
                                    <input type="text" name="kode_pbl"
                                        class="form-control @error('kode_pbl')is-invalid @enderror"
                                        placeholder="kode PBL">
                                    @error('kode_pbl')
                                        <div class="invalid-feedback" role="alert">
                                            <span>{{ $message }}</span>
                                        </div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="nip">Dosen Pengampu</label>
                                    <input type="text" name="dosen_pengampu" id="dosen_pengampu" class="form-control" placeholder="Dosen Pengampu">
                                    <input type="hidden" name="nip1" id="nip1">
                                    <input type="hidden" name="kode_mata_kuliah" id="kode_mata_kuliah">
                                </div>
                                <div class="form-group">
                                    <label for="nip">Proyek Manajer</label>
                                    <input type="text" name="nip" id="nip" class="form-control" placeholder="Project Manager">
                                </div>
                                <input type="hidden" id="hidden_nip_dosen" name="nip">
                                <div class="form-group">
                                    <label>Judul PBL</label>
                                    <input type="text" name="judul_project" class="form-control" placeholder="judul PBL">
                                </div>
                                <div class="form-group row">
                                <div class="col-md-6">
                                    <label for="tahun_akademik">Tahun Akademik</label>
                                        <select name="tahun_akademik" class="form-control" id="tahun_akademik">
                                            <?php
                                            
                                            $tahun_sekarang = date("Y");
                                            
                                            for ($i = $tahun_sekarang; $i >= $tahun_sekarang - 1; $i--) {
                                                $tahun_sebelumnya = $i - 1;
                                                echo "<option value='$tahun_sebelumnya/$i'>$tahun_sebelumnya/$i</option>";
                                                }
                                            ?>
                                        </select>
                                </div>
                                    <div class="col-md-6">
                                        <label for="jenis_usulan">Jenis Usulan</label>
                                        <select name="jenis_usulan" id="jenis_usulan" class="form-control">
                                            <option value="1">Software</option>
                                            <option value="2">Hardware</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-md-6">
                                        <label for="semester">Semester</label>
                                        <input type="number" name="semester" class="form-control" id="semester" placeholder="semester">
                                    </div>
                                    <div class="col-md-6">
                                        <label for="tipe_pendanaan">Tipe Pendanaan</label>
                                        <select name="tipe_pendanaan" id="tipe_pendanaan" class="form-control">
                                            <option value="1">Berbayar</option>
                                            <option value="2">Non Berbayar</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-md-6">
                                        <label for="tanggal_mulai">Tanggal Mulai</label>
                                        <input type="date" name="tanggal_mulai" class="form-control" id="tanggal_mulai">
                                    </div>
                                    <div class="col-md-6">
                                        <label for="tanggal_akhir">Tanggal Selesai</label>
                                        <input type="date" name="tanggal_akhir" class="form-control" id="tanggal_akhir">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Waktu Pengerjaan</label>
                                    <input type="text" name="waktu_pengerjaan" class="form-control" placeholder="waktu pengerjaan" readonly>
                                </div>
                                <div class="form-group">
                                    <label>Gambaran Proyek</label>
                                    <input type="text" name="desain_umum" class="form-control" placeholder="desain umum">
                                </div>
                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-info btn-block btn-flat"><i class="fa fa-save"></i>
                                    Simpan</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('js')
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const tanggalMulaiInput = document.getElementById('tanggal_mulai');
        const tanggalSelesaiInput = document.getElementById('tanggal_akhir');
        const waktuPengerjaanInput = document.getElementsByName('waktu_pengerjaan')[0];

        function formatDate(date) {
            const options = { day: 'numeric', month: 'short', year: 'numeric' };
            return new Date(date).toLocaleDateString('id-ID', options);
        }

        function updateWaktuPengerjaan() {
            const tanggalMulai = tanggalMulaiInput.value;
            const tanggalSelesai = tanggalSelesaiInput.value;
            if (tanggalMulai && tanggalSelesai) {
                const waktuMulaiFormatted = formatDate(tanggalMulai);
                const waktuSelesaiFormatted = formatDate(tanggalSelesai);
                waktuPengerjaanInput.value = `${waktuMulaiFormatted} - ${waktuSelesaiFormatted}`;
            }
        }

        updateWaktuPengerjaan();

        tanggalMulaiInput.addEventListener('change', updateWaktuPengerjaan);
        tanggalSelesaiInput.addEventListener('change', updateWaktuPengerjaan);
    });

    $(document).ready(function() {
    $('#nip').autocomplete({
        source: function(request, response) {
            $.ajax({
                url: '/Search',
                dataType: 'json',
                data: {
                    term: request.term
                },
                success: function(data) {
                    response($.map(data, function(item) {
                        var labelHtml = item.nama_dosen + ' - ' + item.nip; 
                        return {
                            label: labelHtml, 
                            value: item.nama_dosen,
                            nip: item.nip 
                        };
                    }));
                }
            });
        },
        minLength: 2, 
        open: function(event, ui) {
            $(this).autocomplete("widget").css({
                "width": "auto",
                "padding": "10px",
                "border": "1px solid #ccc",
                "list-style": "none",
                "border-radius": "5px",
                "box-shadow": "0 4px 8px 0 rgba(0,0,0,0.2)",
                "background-color": "#fff",
                "position": "absolute",
                "z-index": "1000"
            });
        },
        select: function(event, ui) {
            $(this).val(ui.item.value);
            $('#hidden_nip_dosen').val(ui.item.nip); 
            return false; 
        }
    });
});

$(document).ready(function() {
    $('#dosen_pengampu').autocomplete({
        source: function(request, response) {
            $.ajax({
                url: '/Dosen_Pengampu', // Sesuaikan dengan URL endpoint Anda
                dataType: 'json',
                data: {
                    term: request.term
                },
                success: function(data) {
                    response($.map(data, function(item) {
                        var labelHtml = item.label;
                        return {
                            label: labelHtml,
                            value: item.value,
                            kode_mata_kuliah: item.kode_mata_kuliah,
                            nip: item.nip
                        };
                    }));
                }
            });
        },
        select: function(event, ui) {
            $('#kode_mata_kuliah').val(ui.item.kode_mata_kuliah);
            $('#nip1').val(ui.item.nip);
            // Menambahkan input baru setiap kali dosen pengampu dipilih
            addDosenInput(ui.item.label, ui.item.nip, ui.item.value, ui.item.kode_mata_kuliah);
            return false;
        },
        minLength: 2,
        open: function(event, ui) {
            $(this).autocomplete("widget").css({
                "width": "auto",
                "padding": "10px",
                "border": "1px solid #ccc",
                "list-style": "none",
                "border-radius": "5px",
                "box-shadow": "0 4px 8px 0 rgba(0,0,0,0.2)",
                "background-color": "#fff",
                "position": "absolute",
                "z-index": "1000"
            });
        }
    });

    $('#clearValue2').click(function() {
        $('#dosen_pengampu').val('');
        $('#selectedValue2').text('');
        $(this).hide();
    });

    // Function to add new dosen pengampu input dynamically
    function addDosenInput(label, nip, value, kodeMataKuliah) {
        if (nip) { // Memastikan NIP tidak kosong sebelum menambahkan input
            var dosenHtml = `
            <div class="form-group d-flex align-items-center">
                <div>
                    <span class="clearValue2 mr-3" style="cursor: pointer;">
                        <i class="fas fa-times"></i>
                    </span>
                </div>
                <input type="text" class="form-control dosen_pengampu flex-grow-1" value="${value}" readonly>
                <input type="hidden" class="hidden_nip" name="nip1[]" value="${nip}">
                <input type="hidden" class="hidden_kode_mata_kuliah" name="kode_mata_kuliah[]" value="${kodeMataKuliah}">
            </div>`;
            $('#dosen_pengampu').closest('.form-group').after(dosenHtml);
        }

        $('#dosen_pengampu').val('');
        $('#selectedValue2').text('');
        $('#clearValue2').hide();
    }

    // Dynamic event delegation for clearing dosen pengampu input
    $(document).on('click', '.clearValue2', function() {
        $(this).closest('.form-group').remove();
    });
});


</script>
@endpush

resources/views/admin/index.blade.php
@extends('layouts.app')
@push('css')
    <!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('') }}plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="{{ asset('') }}plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="{{ asset('') }}plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
@endpush
@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6 text-uppercase">
                <h4 class="m-0">Daftar Judul PBL</h4>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                </ol>
            </div>
        </div>
    </div>
</div>
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">Data PBL</h3>
                        <div class="card-tools">
                            <a href="{{ route('manage-admin.create') }}" class="btn btn-tool"><i
                                    class="fas fa-plus-circle"></i></a>
                        </div>
                    </div>
                    <div class="card-body">
                        <table id="datatable-main" class="table table-bordered table-striped">
                            <thead>
                                <th>No</th>
                                <th>Proyek & Anggota Kelompok</th>
                                <th>Tahun Akademik & Semester</th>
                                <th>Waktu</th>
                                <th>Progres</th>
                                <th>Aksi</th>
                            </thead>
                            <tbody>
                                @foreach ($projects as $project)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>
                                            <p>{{ $project->judul_project }}</p>
                                            @foreach ($project->mahasiswa as $mahasiswa)
                                                <p>{{ $loop->iteration }}. {{ $mahasiswa->nama_lengkap }} -
                                                    {{ $mahasiswa->nim }}</p>
                                            @endforeach
                                        </td>
                                        <td>{{ $project->tahun_akademik }} - {{ $project->semester }}</td>
                                        <td>{{ $project->waktu_pengerjaan }}</td>
                                        <td>
                                            <div class="progress progress-sm">
                                                <div class="progress-bar bg-success" role="progressbar" aria-valuenow="{{ $project->overallProgress }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ $project->overallProgress }}%"></div>
                                            </div>
                                            <small>{{ $project->overallProgress }}% Selesai</small>
                                        </td>
                                        <td>
                                            <button type="button" class="btn btn-block btn-sm btn-outline-info"
                                                data-toggle="dropdown">
                                                <i class="fas fa-cog"></i>
                                            </button>
                                            <div class="dropdown-menu" role="menu">
                                                <a class="dropdown-item"
                                                    href="{{ route('manage-admin.edit', $project->project_id) }}">Edit</a>
                                                <form method="POST"
                                                    action="{{ route('manage-admin.destroy', $project->project_id) }}">
                                                    @csrf
                                                    @method('DELETE')
                                                    <a class="dropdown-item confirm-button" href="#">Hapus</a>
                                                </form>
                                                <a class="dropdown-item"
                                                    href="{{ route('manage-plotting.edit', $project->project_id, $project->nip) }}">Plotting</a>
                                                <a class="dropdown-item"
                                                    href="{{ route('manage-plotting.show', $project->project_id, $project->nip) }}">Detail</a>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/listnilai.blade.php
@extends('layouts.app')
@push('css')
    <!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('') }}plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="{{ asset('') }}plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="{{ asset('') }}plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
@endpush
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6 text-uppercase">
                    <h4 class="m-0">List Judul PBL</h4>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-primary card-outline">
                        <div class="card-header">
                            <h3 class="card-title">Data PBL</h3>
                            <div class="card-tools">
                                <a href="{{ route('manage-admin.create') }}" class="btn btn-tool"><i
                                        class="fas fa-plus-circle"></i></a>
                            </div>
                        </div>
                        <div class="card-body">
                            <table id="datatable-main" class="table table-bordered table-striped">
                                <thead>
                                    <th>Waktu</th>
                                    <th>Tahun Akademik</th>
                                    <th>Judul Proyek</th>
                                    <th>Gambaran Proyek</th>
                                    <th>Aksi</th>
                                </thead>
                                <tbody>
                                    @foreach ($projects as $project)
                                        <tr>
                                            <td>{{ $project->waktu_pengerjaan }}</td>
                                            <td>{{ $project->tahun_akademik }}</td>
                                            <td>{{ $project->judul_project }}</td>
                                            <td>{{ $project->desain_umum }}</td>
                                            <td>
                                                <button type="button" class="btn btn-block btn-sm btn-outline-info"
                                                    data-toggle="dropdown"><i class="fas fa-cog"></i>
                                                </button>
                                                <div class="dropdown-menu" role="menu">
                                                    <a class="dropdown-item" href="{{ route('manage-admin.edit', $project->project_id) }}">Edit</a>
                                                    <form method="POST"
                                                    action="{{ route('manage-menu.destroy', $project->project_id) }}">
                                                        @csrf
                                                        @method('DELETE')
                                                        <a class="dropdown-item confirm-button" href="#">Hapus</a>
                                                    </form>
                                                    <a class="dropdown-item" href="{{ route('manage-admin.plotting') }}">Plotting</a>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection